# Generated by Django 2.0.8 on 2019-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190711_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
