# Generated by Django 2.0.8 on 2019-07-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190713_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo.PNG', null=True, upload_to='profile_pics/'),
        ),
    ]
