# Generated by Django 2.0.8 on 2019-07-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
